version: '3.8'

services:
    web:
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn config.wsgi -b 0.0.0.0:8000
        volumes:
            - .:/code
        working_dir: /code
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - "DJANGO_SECRET_KEY=bi&uge+fe51_5g!d7@00)fx3&f&!z()(7$$(wy8ihuv$$^lo&(r&"
            - "DJANGO_DEBUG=True"
            - "DJANGO_SECURE_SSL_REDIRECT=False"  
            - "DJANGO_SECURE_HSTS_SECONDS=0"
            - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
            - "DJANGO_SECURE_HSTS_PRELOAD=False"   
            - "SESSION_COOKIE_SECURE=False"
            - "CSRF_COOKIE_SECURE=False"        
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
    postgres_data:
